const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Your API',
    description: 'Generated by swagger-autogen',
  },
  host: 'localhost:5000',
  schemes: ['http'],
  securityDefinitions: {
    bearerAuth: {
      type: 'apiKey',
      in: 'header',
      name: 'Authorization',
      description:
        'Enter your JWT token in the format **Bearer &lt;token&gt;**',
    },
  },
  security: [
    {
      bearerAuth: [],
    },
  ],
  tags: [],
};

const outputFile = '../../swagger-output.json';
// const endpointsFiles = ['../routes/router.ts'];
const endpointsFiles = ['../index.ts'];

swaggerAutogen(outputFile, endpointsFiles, doc);
