import tiktok from '@/assets/social_medias/tiktok.png';
import youtube from '@/assets/social_medias/youtube.png';
import instagram from '@/assets/social_medias/instagram.png';
import facebook from '@/assets/social_medias/facebook.png';
import InfluencerImg from '@/assets/influencer.jpg';
import { LuInstagram } from 'react-icons/lu';
import { FaTiktok } from 'react-icons/fa';
import { FaFacebookF } from 'react-icons/fa6';
import { IoLogoYoutube } from 'react-icons/io';
export const DEFAULT_CAMPAIGN_IMAGE = InfluencerImg;
export const SUPPORTED_SOCIAL_MEDIAS: {
  icon: any;
  name: 'tiktok' | 'instagram' | 'youtube' | 'facebook';
  description: string;
  svg: any;
  background: string;
  disabled?: boolean;
}[] = [
  {
    icon: instagram,
    name: 'instagram',
    description:
      'Suitable to target audience using aesthetically pleasing content',
    svg: LuInstagram,
    background: 'instagram-background',
    disabled: false,
  },
  {
    icon: tiktok,
    name: 'tiktok',
    description:
      'Suitable to target younger audience with short entertaining videos',
    svg: FaTiktok,
    background: '#000000',
    disabled: false,
  },
  {
    icon: youtube,
    name: 'youtube',
    description:
      'Suitable to educate your audience with longer informational video',
    svg: IoLogoYoutube,
    background: '#FE0808',
    disabled: true,
  },
  {
    icon: facebook,
    name: 'facebook',
    description: 'Suitable to target older audience using longer reviews',
    svg: FaFacebookF,
    background: '#405AA2',
    disabled: true,
  },
];

export const CAMPAIGN_MODELS = [
  {
    id: '1',
    title: 'Product Awareness',
    description:
      'Build awareness for new or existing products in your e-commerce store',
  },
  {
    id: '2',
    title: 'Traffic & Conversion',
    description:
      'Drive traffic to your e-commerce store and convert visitors into customers',
  },
  {
    id: '3',
    title: 'Content Creation',
    description:
      'Generate high-quality content featuring your products for future marketing use',
  },
  {
    id: '4',
    title: 'Social Proof',
    description:
      'Build credibility through authentic influencer endorsements and reviews',
  },
  {
    id: '5',
    title: 'Product Launch',
    description:
      'Launch a new product line or collection with influencer support',
  },
  {
    id: '6',
    title: 'Sales & Promotion',
    description: `Drive sales through special promotions, discounts, or affiliate links`,
  },
  {
    id: '7',
    title: 'Affiliate Marketing Campaigns',
    description: `Generate unique affiliate links and discount codes within your platform.Provide real-time tracking of clicks, conversions, and revenue generated by each influencer.`,
  },
  {
    id: '8',
    title: 'Performance Based Campaign',
    description: `Track website traffic and reward creators based on their performances, on top of the basic payout for sponsored posts.`,
  },
];
